---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Refresh user password
      user:
        name: db_access_user
        update_password: always
        password: $6$8FB2ZfY/$gwkv1HG7fOuZ0Qoakz0bR3QCHlM3TRrjgKTK49nAQuiDpwWtJDuJfNiRHh4mJw/uvLfSin6CYZSi43t3Ugky91
#        password: "{{ newpassword|password_hash('sha512') }}"
