---
- name: playbook for simple 2.3 TB partition
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: create partition
      command: /usr/sbin/parted -s /dev/sdd mklabel gpt mkpart primary "1 -1"
    - name: task for creating volume group
      lvg:
          vg: vg_data
          pvs: /dev/sdd1
          state: present

    - name: task for creating logical volume
      lvol:
          vg: vg_data
          lv: lv_data
          size: 2.25t
          force: yes

    - name: Create directory /data if does not exist
      file:
        path: /data
        state: directory
        mode: '0755'

    - name: format with xfs filesystem
      filesystem:
        fstype: xfs
        dev: /dev/vg_data/lv_data

    - name: mount the lv on /data
      mount:
        path: /data
        src: /dev/vg_data/lv_data
        fstype: xfs
        state: mounted
...

